name: food_app
version: 0.1.0
publish_to: 'none'
description: Main project package.

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  main_menu:
    path: ./features/main_menu
  core:
    path: ./core
  data:
    path: ./data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
