name: dishes_menu
version: 0.0.1
publish_to: none
description: Dishes menu feature.

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  detailed_page:
    path: ../detailed_page
  core:
    path: ../../../core
  domain: 
    path: ../../../domain
  core_ui:
    path: ../../../core_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
