name: shopping_cart
version: 0.0.1
publish_to: none
description: Shopping cart feature.

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  core:
    path: ../../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
