name: sign_up_screen
version: 0.0.1
publish_to: none
description: Sign up screen feature.

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #main dependencies
  core_ui:
    path: ../../../core_ui
  core:
    path: ../../../core
  domain: 
    path: ../../../domain
  navigation:
    path: ../../../navigation

  #user features
  home_screen:
    path: ../../user/home_screen

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
